perl /data/bioprojects/www.genomexploit/genomeLoader.pl --cleandb --db Holospora --chromosome "/data/bioprojects/Holospora/genomes/Holospora curviuscula.tagged.gb"
perl /data/bioprojects/www.genomexploit/genomeLoader.pl --db Holospora --chromosome "/data/bioprojects/Holospora/genomes/Holospora undulata.tagged.gb"
perl /data/bioprojects/www.genomexploit/genomeLoader.pl --db Holospora --chromosome "/data/bioprojects/Holospora/genomes/Holospora obtusa F1.gb"

perl /data/bioprojects/www.genomexploit/genomeLoader.pl --db Holospora --chromosome "/data/bioprojects/Holospora/genomes/Anaplasma centrale str. Israel.gb"
perl /data/bioprojects/www.genomexploit/genomeLoader.pl --db Holospora --chromosome "/data/bioprojects/Holospora/genomes/Anaplasma marginale str. Florida.gb"
perl /data/bioprojects/www.genomexploit/genomeLoader.pl --db Holospora --chromosome "/data/bioprojects/Holospora/genomes/Anaplasma marginale str. St. Maries.gb"
perl /data/bioprojects/www.genomexploit/genomeLoader.pl --db Holospora --chromosome "/data/bioprojects/Holospora/genomes/Anaplasma phagocytophilum HZ.gb"
perl /data/bioprojects/www.genomexploit/genomeLoader.pl --db Holospora --chromosome "/data/bioprojects/Holospora/genomes/Anaplasma phagocytophilum str. Dog2.gb"
perl /data/bioprojects/www.genomexploit/genomeLoader.pl --db Holospora --chromosome "/data/bioprojects/Holospora/genomes/Anaplasma phagocytophilum str. HZ2.gb"
perl /data/bioprojects/www.genomexploit/genomeLoader.pl --db Holospora --chromosome "/data/bioprojects/Holospora/genomes/Anaplasma phagocytophilum str. JM.gb"
perl /data/bioprojects/www.genomexploit/genomeLoader.pl --db Holospora --chromosome "/data/bioprojects/Holospora/genomes/Candidatus Hodgkinia cicadicola Dsem.gb"
perl /data/bioprojects/www.genomexploit/genomeLoader.pl --db Holospora --chromosome "/data/bioprojects/Holospora/genomes/Candidatus Midichloria mitochondrii IricVA.gb"
perl /data/bioprojects/www.genomexploit/genomeLoader.pl --db Holospora --chromosome "/data/bioprojects/Holospora/genomes/Ehrlichia canis str. Jake.gb"
perl /data/bioprojects/www.genomexploit/genomeLoader.pl --db Holospora --chromosome "/data/bioprojects/Holospora/genomes/Ehrlichia chaffeensis str. Arkansas.gb"
perl /data/bioprojects/www.genomexploit/genomeLoader.pl --db Holospora --chromosome "/data/bioprojects/Holospora/genomes/Ehrlichia chaffeensis str. Sapulpa.gb"
perl /data/bioprojects/www.genomexploit/genomeLoader.pl --db Holospora --chromosome "/data/bioprojects/Holospora/genomes/Ehrlichia ruminantium strain Welgevonden.gb"
perl /data/bioprojects/www.genomexploit/genomeLoader.pl --db Holospora --chromosome "/data/bioprojects/Holospora/genomes/Ehrlichia ruminantium str. Gardel.gb"
perl /data/bioprojects/www.genomexploit/genomeLoader.pl --db Holospora --chromosome "/data/bioprojects/Holospora/genomes/Neorickettsia risticii str. Illinois.gb"
perl /data/bioprojects/www.genomexploit/genomeLoader.pl --db Holospora --chromosome "/data/bioprojects/Holospora/genomes/Neorickettsia sennetsu strain Miyayama.gb"
perl /data/bioprojects/www.genomexploit/genomeLoader.pl --db Holospora --chromosome "/data/bioprojects/Holospora/genomes/Orientia tsutsugamushi Boryong.tagged.gb"
perl /data/bioprojects/www.genomexploit/genomeLoader.pl --db Holospora --chromosome "/data/bioprojects/Holospora/genomes/Orientia tsutsugamushi str. Ikeda.gb"
perl /data/bioprojects/www.genomexploit/genomeLoader.pl --db Holospora --chromosome "/data/bioprojects/Holospora/genomes/Rickettsia africae ESF-5.gb"  --plasmid "/data/bioprojects/Holospora/genomes/Rickettsia africae ESF-5 plasmid pRAF.gb"
perl /data/bioprojects/www.genomexploit/genomeLoader.pl --db Holospora --chromosome "/data/bioprojects/Holospora/genomes/Rickettsia akari str. Hartford.gb"
perl /data/bioprojects/www.genomexploit/genomeLoader.pl --db Holospora --chromosome "/data/bioprojects/Holospora/genomes/Rickettsia australis str. Cutlack.gb"  --plasmid "/data/bioprojects/Holospora/genomes/Rickettsia australis str. Cutlack Plasmid01.gb"
perl /data/bioprojects/www.genomexploit/genomeLoader.pl --db Holospora --chromosome "/data/bioprojects/Holospora/genomes/Rickettsia bellii OSU 85-389.gb"
perl /data/bioprojects/www.genomexploit/genomeLoader.pl --db Holospora --chromosome "/data/bioprojects/Holospora/genomes/Rickettsia bellii RML369-C.gb"
perl /data/bioprojects/www.genomexploit/genomeLoader.pl --db Holospora --chromosome "/data/bioprojects/Holospora/genomes/Rickettsia canadensis str. McKiel.gb"
perl /data/bioprojects/www.genomexploit/genomeLoader.pl --db Holospora --chromosome "/data/bioprojects/Holospora/genomes/Rickettsia conorii str. Malish 7.gb"
perl /data/bioprojects/www.genomexploit/genomeLoader.pl --db Holospora --chromosome "/data/bioprojects/Holospora/genomes/Rickettsia felis URRWXCal2.gb"  --plasmid "/data/bioprojects/Holospora/genomes/Rickettsia felis URRWXCal2 plasmid pRFdelta.gb" "/data/bioprojects/Holospora/genomes/Rickettsia felis URRWXCal2 plasmid pRF.gb"
perl /data/bioprojects/www.genomexploit/genomeLoader.pl --db Holospora --chromosome "/data/bioprojects/Holospora/genomes/Rickettsia heilongjiangensis 054.gb"
perl /data/bioprojects/www.genomexploit/genomeLoader.pl --db Holospora --chromosome "/data/bioprojects/Holospora/genomes/Rickettsia massiliae MTU5.gb"  --plasmid "/data/bioprojects/Holospora/genomes/Rickettsia massiliae MTU5 plasmid pRMA.gb"
perl /data/bioprojects/www.genomexploit/genomeLoader.pl --db Holospora --chromosome "/data/bioprojects/Holospora/genomes/Rickettsia massiliae str. AZT80.gb"  --plasmid "/data/bioprojects/Holospora/genomes/Rickettsia massiliae str. AZT80 plasmid pRMB.gb"
perl /data/bioprojects/www.genomexploit/genomeLoader.pl --db Holospora --chromosome "/data/bioprojects/Holospora/genomes/Rickettsia montanensis str. OSU 85-930.gb"
perl /data/bioprojects/www.genomexploit/genomeLoader.pl --db Holospora --chromosome "/data/bioprojects/Holospora/genomes/Rickettsia parkeri str. Portsmouth.gb"
perl /data/bioprojects/www.genomexploit/genomeLoader.pl --db Holospora --chromosome "/data/bioprojects/Holospora/genomes/Rickettsia peacockii str. Rustic.gb"  --plasmid "/data/bioprojects/Holospora/genomes/Rickettsia peacockii str. Rustic plasmid pRPR.gb"
perl /data/bioprojects/www.genomexploit/genomeLoader.pl --db Holospora --chromosome "/data/bioprojects/Holospora/genomes/Rickettsia philipii str. 364D.gb"
perl /data/bioprojects/www.genomexploit/genomeLoader.pl --db Holospora --chromosome "/data/bioprojects/Holospora/genomes/Rickettsia prowazekii str. Breinl.gb"
perl /data/bioprojects/www.genomexploit/genomeLoader.pl --db Holospora --chromosome "/data/bioprojects/Holospora/genomes/Rickettsia prowazekii str. BuV67-CWPP.gb"
perl /data/bioprojects/www.genomexploit/genomeLoader.pl --db Holospora --chromosome "/data/bioprojects/Holospora/genomes/Rickettsia prowazekii str. Chernikova.gb"
perl /data/bioprojects/www.genomexploit/genomeLoader.pl --db Holospora --chromosome "/data/bioprojects/Holospora/genomes/Rickettsia prowazekii str. Dachau.gb"
perl /data/bioprojects/www.genomexploit/genomeLoader.pl --db Holospora --chromosome "/data/bioprojects/Holospora/genomes/Rickettsia prowazekii str. RpGvF24.gb"
perl /data/bioprojects/www.genomexploit/genomeLoader.pl --db Holospora --chromosome "/data/bioprojects/Holospora/genomes/Rickettsia rhipicephali str. 3-7-female6-CWPP.gb"  --plasmid "/data/bioprojects/Holospora/genomes/Rickettsia rhipicephali str. 3-7-female6-CWPP plasmid pMCC_1.gb"
perl /data/bioprojects/www.genomexploit/genomeLoader.pl --db Holospora --chromosome "/data/bioprojects/Holospora/genomes/Rickettsia rickettsii str. Arizona.gb"
perl /data/bioprojects/www.genomexploit/genomeLoader.pl --db Holospora --chromosome "/data/bioprojects/Holospora/genomes/Rickettsia rickettsii str. Brazil.gb"
perl /data/bioprojects/www.genomexploit/genomeLoader.pl --db Holospora --chromosome "/data/bioprojects/Holospora/genomes/Rickettsia rickettsii str. Colombia.gb"
perl /data/bioprojects/www.genomexploit/genomeLoader.pl --db Holospora --chromosome "/data/bioprojects/Holospora/genomes/Rickettsia rickettsii str. Iowa.gb"
perl /data/bioprojects/www.genomexploit/genomeLoader.pl --db Holospora --chromosome "/data/bioprojects/Holospora/genomes/Rickettsia rickettsii str. 'Sheila Smith'.gb"
perl /data/bioprojects/www.genomexploit/genomeLoader.pl --db Holospora --chromosome "/data/bioprojects/Holospora/genomes/Rickettsia sibirica 246.gb"
perl /data/bioprojects/www.genomexploit/genomeLoader.pl --db Holospora --chromosome "/data/bioprojects/Holospora/genomes/Rickettsia slovaca 13-B.gb"
perl /data/bioprojects/www.genomexploit/genomeLoader.pl --db Holospora --chromosome "/data/bioprojects/Holospora/genomes/Rickettsia slovaca str. D-CWPP.gb"
perl /data/bioprojects/www.genomexploit/genomeLoader.pl --db Holospora --chromosome "/data/bioprojects/Holospora/genomes/Rickettsia typhi str. B9991CWPP.gb"
perl /data/bioprojects/www.genomexploit/genomeLoader.pl --db Holospora --chromosome "/data/bioprojects/Holospora/genomes/Rickettsia typhi str. Wilmington.gb"
perl /data/bioprojects/www.genomexploit/genomeLoader.pl --db Holospora --chromosome "/data/bioprojects/Holospora/genomes/Wolbachia endosymbiont of Culex quinquefasciatus Pel strain wPip.gb"
perl /data/bioprojects/www.genomexploit/genomeLoader.pl --db Holospora --chromosome "/data/bioprojects/Holospora/genomes/Wolbachia endosymbiont of Drosophila melanogaster.gb"
perl /data/bioprojects/www.genomexploit/genomeLoader.pl --db Holospora --chromosome "/data/bioprojects/Holospora/genomes/Wolbachia endosymbiont of Drosophila simulans wHa.gb"
perl /data/bioprojects/www.genomexploit/genomeLoader.pl --db Holospora --chromosome "/data/bioprojects/Holospora/genomes/Wolbachia endosymbiont of Drosophila simulans wNo.gb"
perl /data/bioprojects/www.genomexploit/genomeLoader.pl --db Holospora --chromosome "/data/bioprojects/Holospora/genomes/Wolbachia endosymbiont strain TRS of Brugia malayi.gb"

